### ISSUE TITLE
[Improvement] Allow for private key to be created in a target directory

### ISSUE THREAD

**Issue by chasefleming** [onflow/flowkit#47]
### Issue to be solved

You can save the state to a path, but the private key creation only happens at the root level. This means your config and key can be in different locations after saving.

### Suggest A Solution

We need a way to give the target directory to the private key creation so it occurs in the same place as the config is created.

**Comment by jribbink** [comment]
The other workaround is potentially to just make the default account/emulator account an argument instead of the target driectory.  This could potentially provide more control to the end user while also solving this issue.  (i.e. right now everyone is forced to use file keys for emulator account, maybe they don't want to do this, etc.)

**Comment by chasefleming** [comment]
@bjartek any thoughts on this? Could be something like `flowkit.Init(readerWriter, NewEmulatorAccount(...))`

Or, separately creating the account could be an additional step like:

```
state, err := flowkit.Init(readerWriter)
state.AddAccount(...)
```

That being said if you prefer what was on the PR that would work as well, which was `flowkit.Init(readerWriter, crypto.ECDSA_P256, crypto.SHA3_256, "")`

**Comment by chasefleming** [comment]
@bjartek any preferences here?

**Comment by bjartek** [comment]
I dont really use keys in files. I find it easier to use env var substitution to keep things secure.
